version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework:spring-web
        versions:
          - ">= 6"
